# Development docker-compose. Assuming the folders of BBF/API are in the folders
# relative to this repository, point /etc/hosts to mace 127.0.0.1 and connect
# to http://mace:88

version: '3.8'

services:
  traefik:
    image: traefik:v2.9.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "88:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mace-api:
    build:
      context: ../mace-api
    environment:
      - DB_HOST=macemap-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=postgres
      - DB_PREFIX=postgresql+asyncpg
    depends_on:
        - macemap-db
    volumes:
      - ../mace-api/app:/app/app

  macemap-bff:
    build:
      context: ../macemap-bff
    environment:
      - KEYCLOAK_CLIENT_ID=macemap-local
      - KEYCLOAK_REALM=MACE
      - KEYCLOAK_URL=https://enac-it4r-sso.epfl.ch/
      - MACE_API_URL=http://mace-api:8000
    labels:
      - "traefik.http.routers.macemap-bff.rule=Host(`mace`) && PathPrefix(`/api`)"
      - "traefik.http.services.macemap-bff.loadbalancer.server.port=8000"
    volumes:
      - ../macemap-bff/app:/app/app
    entrypoint: ["uvicorn", "--host=0.0.0.0",
              "--timeout-keep-alive=0", "app.main:app", "--reload"]

  macemap-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Uses the dockerfile containing yarn dev
    labels:
      - "traefik.http.routers.macemap-ui.rule=Host(`mace`)"
      - "traefik.http.services.macemap-ui.loadbalancer.server.port=5173"
    volumes:
      - ../macemap-ui:/app

  macemap-db:
    image: postgis/postgis:16-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - macemap-db-data:/var/lib/postgresql/data

volumes:
  macemap-db-data:
